# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' alphaPeptMs2GenericEnsemble
#'
#' This function returns a predicted fragment ion spectrum
#' of a given peptide sequence.
#'
#' @param peptide amino acid sequence, e.g., \code{"LGGNEQVTR"}
#' @param precursorCharge precursor charge, e.g., 2.
#' @param collisionEnergy the collision energy in [eV]?.
#' @param instrument  an integer defining the instrument: 0 - QE;
#' 1 - Lumos; 2 - timsTOF; 3 - SciexTOF.
#' @param verbose provides grpc proteobuf output.
#' @param url GRPC url, e.g., localhost:9990 or \url{dlomix.fgcz.uzh.ch:8080}.
#' 
#' @examples
#'   koina::alphaPeptMs2GenericEnsemble("LGGNEQVTR", collisionEnergy = 0.25, precursorCharge = 2)       
#' 
#' @export
alphaPeptMs2GenericEnsemble <- function(peptide, collisionEnergy = 0.25, precursorCharge = 2L, instrument = 0L, verbose = FALSE, url = "dlomix.fgcz.uzh.ch:8080") {
    .Call(`_koina_alphaPeptMs2GenericEnsemble`, peptide, collisionEnergy, precursorCharge, instrument, verbose, url)
}

#' prosit2019Intensity
#'
#' This function returns a predicted fragment ion spectrum
#' of a given peptide sequence.
#'
#' @inheritParams alphaPeptMs2GenericEnsemble
#' @params usesll boolean use ssl, default is set to \code{TRUE}.
#'
#' @examples
#'
#'  koina::prosit2019Intensity("LKEATIQLDELNQK",
#'    collisionEnergy = 25, precursorCharge = 2L, verbose = TRUE, usessl=TRUE,
#'    url = "koina.proteomicsdb.org:443") |> head()
#'
#' #   url = "dlomix.fgcz.uzh.ch:8080"
#' 
#' @export
prosit2019Intensity <- function(peptide, collisionEnergy, precursorCharge, verbose = FALSE, usessl = TRUE, url = "koina.proteomicsdb.org:443") {
    .Call(`_koina_prosit2019Intensity`, peptide, collisionEnergy, precursorCharge, verbose, usessl, url)
}

#' Prosit_2019_irt_ensemble
#'
#' @inheritParams alphaPeptMs2GenericEnsemble
#'
#' @examples
#'   koina::prosit2019IrtEnsemble("LGGNEQVTR")       
#' 
#' @export
prosit2019IrtEnsemble <- function(peptide, verbose = FALSE, url = "dlomix.fgcz.uzh.ch:8080") {
    .Call(`_koina_prosit2019IrtEnsemble`, peptide, verbose, url)
}

